menu:
    主页: /
    归档: /archives/
    标签: /tags/
    微博: http://weibo.com/jesseccchen
    GitHub: https://github.com/chenjiangsong

favicon: http://ob3wg7deo.bkt.clouddn.com/batman_1.png
logo: http://ob3wg7deo.bkt.clouddn.com/batman.png

# Comment
# e.g disqus: seansun
disqus: seansun
duoshuo:

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2015
